version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/blogify  
      - .:/app
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
